apiVersion: v1
kind: Pod
metadata:
  name: house-api
  labels:
    app: house-api
    version: v3
spec:
    containers:
    - name: house-api
      image: bundyfx/house-api:1.0.0
      ports:
      - containerPort: 5000