kind: Service
apiVersion: v1
metadata:
  name: house-api-svc-v1
spec:
  type: NodePort
  selector:
    app: house-api
    version: v1
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30002